In [1]:
import numpy as np

In [14]:
def info_array(a):
    print("dimension : ",a.ndim)
    print("Size(number of elements in array  : ",a.size)
    print("Shape : ",a.shape)
    print("Dtype : ",a.dtype)
    

In [2]:
arr1=np.arange(12)

In [3]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
arr1.ndim

1

In [5]:
arr1.size

12

In [6]:
arr1.dtype

dtype('int32')

In [7]:
arr1.shape

(12,)

In [15]:
info_array(arr1)

dimension :  1
Size(number of elements in array  :  12
Shape :  (12,)
Dtype :  int32


In [16]:
arr2=np.arange(64)

In [17]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

### Numpy functions

In [20]:
arr3= np.linspace(1,2,32)
arr3

array([1.        , 1.03225806, 1.06451613, 1.09677419, 1.12903226,
       1.16129032, 1.19354839, 1.22580645, 1.25806452, 1.29032258,
       1.32258065, 1.35483871, 1.38709677, 1.41935484, 1.4516129 ,
       1.48387097, 1.51612903, 1.5483871 , 1.58064516, 1.61290323,
       1.64516129, 1.67741935, 1.70967742, 1.74193548, 1.77419355,
       1.80645161, 1.83870968, 1.87096774, 1.90322581, 1.93548387,
       1.96774194, 2.        ])

In [21]:
arr4=np.linspace(1,5,125)
arr4

array([1.        , 1.03225806, 1.06451613, 1.09677419, 1.12903226,
       1.16129032, 1.19354839, 1.22580645, 1.25806452, 1.29032258,
       1.32258065, 1.35483871, 1.38709677, 1.41935484, 1.4516129 ,
       1.48387097, 1.51612903, 1.5483871 , 1.58064516, 1.61290323,
       1.64516129, 1.67741935, 1.70967742, 1.74193548, 1.77419355,
       1.80645161, 1.83870968, 1.87096774, 1.90322581, 1.93548387,
       1.96774194, 2.        , 2.03225806, 2.06451613, 2.09677419,
       2.12903226, 2.16129032, 2.19354839, 2.22580645, 2.25806452,
       2.29032258, 2.32258065, 2.35483871, 2.38709677, 2.41935484,
       2.4516129 , 2.48387097, 2.51612903, 2.5483871 , 2.58064516,
       2.61290323, 2.64516129, 2.67741935, 2.70967742, 2.74193548,
       2.77419355, 2.80645161, 2.83870968, 2.87096774, 2.90322581,
       2.93548387, 2.96774194, 3.        , 3.03225806, 3.06451613,
       3.09677419, 3.12903226, 3.16129032, 3.19354839, 3.22580645,
       3.25806452, 3.29032258, 3.32258065, 3.35483871, 3.38709

In [23]:
info_array(arr4)

dimension :  1
Size(number of elements in array  :  125
Shape :  (125,)
Dtype :  float64


In [25]:
arr5=np.arange(1,24)
arr5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23])

In [29]:
arr12=np.linkspace(1,100,100,dtype="int").reshape(10,10)

AttributeError: module 'numpy' has no attribute 'linkspace'

In [30]:
arr12=np.linspace(1,100,100,dtype="int").reshape(10,10)

In [31]:
arr12

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [32]:
np.split(arr12,[3,6])

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]]),
 array([[31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
        [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]]),
 array([[ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
        [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])]

In [33]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
arr12.repeat(2)

array([  1,   1,   2,   2,   3,   3,   4,   4,   5,   5,   6,   6,   7,
         7,   8,   8,   9,   9,  10,  10,  11,  11,  12,  12,  13,  13,
        14,  14,  15,  15,  16,  16,  17,  17,  18,  18,  19,  19,  20,
        20,  21,  21,  22,  22,  23,  23,  24,  24,  25,  25,  26,  26,
        27,  27,  28,  28,  29,  29,  30,  30,  31,  31,  32,  32,  33,
        33,  34,  34,  35,  35,  36,  36,  37,  37,  38,  38,  39,  39,
        40,  40,  41,  41,  42,  42,  43,  43,  44,  44,  45,  45,  46,
        46,  47,  47,  48,  48,  49,  49,  50,  50,  51,  51,  52,  52,
        53,  53,  54,  54,  55,  55,  56,  56,  57,  57,  58,  58,  59,
        59,  60,  60,  61,  61,  62,  62,  63,  63,  64,  64,  65,  65,
        66,  66,  67,  67,  68,  68,  69,  69,  70,  70,  71,  71,  72,
        72,  73,  73,  74,  74,  75,  75,  76,  76,  77,  77,  78,  78,
        79,  79,  80,  80,  81,  81,  82,  82,  83,  83,  84,  84,  85,
        85,  86,  86,  87,  87,  88,  88,  89,  89,  90,  90,  9

In [35]:
np.split(arr12,[2,4,6,8],axis=1)

[array([[ 1,  2],
        [11, 12],
        [21, 22],
        [31, 32],
        [41, 42],
        [51, 52],
        [61, 62],
        [71, 72],
        [81, 82],
        [91, 92]]),
 array([[ 3,  4],
        [13, 14],
        [23, 24],
        [33, 34],
        [43, 44],
        [53, 54],
        [63, 64],
        [73, 74],
        [83, 84],
        [93, 94]]),
 array([[ 5,  6],
        [15, 16],
        [25, 26],
        [35, 36],
        [45, 46],
        [55, 56],
        [65, 66],
        [75, 76],
        [85, 86],
        [95, 96]]),
 array([[ 7,  8],
        [17, 18],
        [27, 28],
        [37, 38],
        [47, 48],
        [57, 58],
        [67, 68],
        [77, 78],
        [87, 88],
        [97, 98]]),
 array([[  9,  10],
        [ 19,  20],
        [ 29,  30],
        [ 39,  40],
        [ 49,  50],
        [ 59,  60],
        [ 69,  70],
        [ 79,  80],
        [ 89,  90],
        [ 99, 100]])]

sp1,sp2,sp3 =np.split(arr12,[4 , 7], axis=1)

In [40]:
arr12

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [36]:
sp1,sp2,sp3 =np.split(arr12,[4,7],axis=1)

In [37]:
sp1

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44],
       [51, 52, 53, 54],
       [61, 62, 63, 64],
       [71, 72, 73, 74],
       [81, 82, 83, 84],
       [91, 92, 93, 94]])

In [38]:
sp2

array([[ 5,  6,  7],
       [15, 16, 17],
       [25, 26, 27],
       [35, 36, 37],
       [45, 46, 47],
       [55, 56, 57],
       [65, 66, 67],
       [75, 76, 77],
       [85, 86, 87],
       [95, 96, 97]])

In [39]:
sp3

array([[  8,   9,  10],
       [ 18,  19,  20],
       [ 28,  29,  30],
       [ 38,  39,  40],
       [ 48,  49,  50],
       [ 58,  59,  60],
       [ 68,  69,  70],
       [ 78,  79,  80],
       [ 88,  89,  90],
       [ 98,  99, 100]])