In [1]:
a=2

In [2]:
b=2

In [3]:
c=a+b

In [4]:
c

4

In [5]:
arr=np.array([1,2,3,4,5,6,7,8])

NameError: name 'np' is not defined

In [6]:
arr

NameError: name 'arr' is not defined

In [9]:
import numpy as np

In [10]:
arr=np.array([1,2,3,4,5,6,7])

In [11]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
arr[4]

5

In [15]:
arr2=np.array([[1,1,2],[5,6,7],[4,6,7]])

In [16]:
arr2

array([[1, 1, 2],
       [5, 6, 7],
       [4, 6, 7]])

In [17]:
arr2.ndim

2

In [18]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
arr.shape

(7,)

In [20]:
arr2.shape

(3, 3)

In [24]:
arr3=np.arange(64)

In [25]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [26]:
arr3.reshape(4,16)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63]])

In [27]:
arr3.reshape(2,32)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63]])

In [29]:
arr3.size

64

In [30]:
arr3.dtype

dtype('int32')

In [31]:
arr1.dtype

NameError: name 'arr1' is not defined

In [32]:
arr2.dtype

dtype('int32')